Add Japanese translation
factmaven/disable-blogging pull request #9
Opened 2016-10-29 15:54 UTC by sectsect

Hi @factmaven 

This pull request fix a few code for translation.
And, add :jp: Japanese translation.

2016-10-29 21:13 UTC, factmaven commented
Excllent job @sectsect! When you look at the `dsbl-ja.po` for the translated text, for example:
```
#: admin/plugin-meta.php:23
msgid "Support"
msgstr "サポート"
```

If I were to make changes to the `plugin-meta.php` file and the word "_Support_" is now on line 30, will the `dsbl-ja.po` need to be updated to reflect that? Like so:
```
#: admin/plugin-meta.php:30
msgid "Support"
msgstr "

2016-10-29 21:17 UTC, ghost requested changes
No need to changes to the `howdy()` function in `functions-extra.php`. See comment.

2016-10-29 21:17 UTC, factmaven commented on includes/functions-extra.php
> -    public function howdy( $wp_admin_bar ) {
No need to changes to the `howdy()` function. I am implementing a universal way to remove greeting from all languages. [See here](https://wordpress.org/support/topic/howdy-greeting/).

2016-10-29 22:59 UTC, sectsect commented
@factmaven

Thank you for confirmation.

> If I were to make changes to the plugin-meta.php file and the word "Support" is now on line 30, will the dsbl-ja.po need to be updated to reflect that? Like so:
> ```
> #: admin/plugin-meta.php:30
> msgid "Support"
> msgstr "サポート"
> ```

You are right.
In that case, you will need to update it in all language files.

> No need to changes to the howdy() function in functions-extra.php. See comment.

Oh, I see.
I reverted the `function howdy()`. https://github.com/factmaven/disable-blogging/pull/9/commits/07d888b829261cc13c4694522cce1593d5ede73d

Please confirm.

2016-10-30 00:37 UTC, ghost approved these changes

2016-10-30 14:45 UTC, factmaven commented on languages/dsbl-ja.po
> +msgstr "<strong>削除</strong>: %s"
According to Google Translate, "削除" means "Delete". I just want to clarify that it should be "Removed" because nothing is actually being deleted.

2016-10-30 14:51 UTC, factmaven commented
Great, thanks for that info. I'll be updating some of the functions for the next update, so the languages would most likely need to be updated. I'll check out the [Poedit](https://poedit.net/download) to update the main `.pot` file that was added in #6.

I was using [Google Translate](https://translate.google.com/) to see the translation form your Japanese. I see that  "削除" means "Delete". I just want to clarify that it should be "Removed" because nothing is actually being deleted. However, I have no experience in Japanese and I know Google Translate isn't always accurate. So I am leaving that expertise to you. Just wanted to make sure I was understanding it correctly.

```
#: admin/settings-page.php:294
msgid "Removed"
msgstr "削除"
```

I've added additional comments to your commits.

2016-10-30 14:57 UTC, factmaven commented on languages/dsbl-ja.po
> +msgstr "削除"
According to Google Translate, "削除" means "Delete". I just want to clarify that it should be "Removed" because nothing is actually being deleted.

2016-10-30 14:57 UTC, factmaven commented on languages/dsbl-ja.po
> +msgstr "<strong>削除</strong>: %s"
According to Google Translate, "削除" means "Delete". I just want to clarify that it should be "Removed" because nothing is actually being deleted.

2016-10-30 18:51 UTC, sectsect commented
> I was using Google Translate to see the translation form your Japanese. I see that "削除" means "Delete". I just want to clarify that it should be "Removed" because nothing is actually being deleted. However, I have no experience in Japanese and I know Google Translate isn't always accurate. So I am leaving that expertise to you. Just wanted to make sure I was understanding it correctly.
> 
> ```
> #: admin/settings-page.php:294
> msgid "Removed"
> msgstr "削除"
> ```

This have a subtle nuance difference in japanese.
In general, many cases both "`Delete`" and "`Remove`" are translated as "`削除`".

But it is also good that "`Removed`" be translated as "`除去`" in a little formal representation.

I commited for this changes.
https://github.com/factmaven/disable-blogging/pull/9/commits/235bb739decdced169cd63fd5c34c4b3bdaa04d5

2016-10-30 18:53 UTC, sectsect commented on languages/dsbl-ja.po
> +msgstr "<strong>削除</strong>: %s"
https://github.com/factmaven/disable-blogging/pull/9#issuecomment-257170364

2016-10-30 18:53 UTC, sectsect commented on languages/dsbl-ja.po
> +msgstr "削除"
https://github.com/factmaven/disable-blogging/pull/9#issuecomment-257170364

2016-10-30 21:07 UTC, factmaven commented
Thanks for clarifying. I figured that's the case which is why I would follow your translation rather than Google's version of it since you're a native speaker.

2016-10-30 21:07 UTC, merged